# Generated by Django 4.0.1 on 2022-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomOrganisme', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
