# Generated by Django 4.0.1 on 2022-01-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeJ', models.TextField(max_length=15)),
                ('dateSoutenance', models.DateField(default='01/01/2022')),
            ],
        ),
    ]
