# Generated by Django 4.0.1 on 2022-01-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_alter_jury_codej'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomE', models.CharField(max_length=20)),
                ('prenomE', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('A', 'Maître assistant A'), ('B', 'Maître assistant B'), ('C', 'Maître de conférence A'), ('D', 'Maître de conférence B'), ('E', 'Professeur')], max_length=20)),
                ('codeJ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury')),
            ],
        ),
    ]
