# Generated by Django 4.0.1 on 2022-01-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_enseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreStage', models.CharField(max_length=40)),
                ('typeStage', models.CharField(choices=[('1CP', 'Stage ouvrier 1CP'), ('1CS', 'Stage technique 1CS'), ('PFE3CS', 'Stage technique PFE 3CS')], max_length=30)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.enseignant')),
                ('jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.organismestage')),
            ],
        ),
    ]
