# Generated by Django 4.0.1 on 2022-01-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=20)),
                ('prenomM', models.CharField(max_length=20)),
                ('poste', models.CharField(max_length=20)),
                ('codeJ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.organismestage')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.stage')),
            ],
        ),
    ]
