# Generated by Django 4.0.1 on 2022-01-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=40)),
                ('prenoms', models.CharField(max_length=40)),
                ('DateNaissance', models.DateField(default='01/01/2022')),
                ('Email', models.EmailField(max_length=254)),
                ('annedEude', models.CharField(choices=[('1CP', '1CPI'), ('1CS', '1CS'), ('PFE3CS', '3CS')], max_length=20)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.stage')),
            ],
        ),
    ]
