# Generated by Django 4.0.1 on 2022-01-24 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_convention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficheeva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteava', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.stage')),
            ],
        ),
    ]
